### PR TITLE
Fix output parsing

### LINKED ISSUE #36: Output parsing not registering for KoTest executions
This issue is going to encompass two issues that currently exist, I think these issues can either be solved together or really closely related.

1. Output parsing doesn't properly register tests passing/failing/skipped

Example output:

```text
2025-06-24T00:05:30.085-0400 [DEBUG] [TestEventLogger] org.example.KotestDescribeSpec > a namespace > a nested namespace > org.example.KotestDescribeSpec.should handle passed assertions PASSED
```

Results in the test not being marked as PASSED, but as FAILED.

2. `--debug` flag to gradlew results in a lot of output, but also less helpful/useful output for the user (most debug logs are noise)

Solution I've been investigating here is using [Gradle init scripts](https://docs.gradle.org/current/userguide/init_scripts.html) (gradle specific solution). By providing an init script via the `-I` or `--init-script` flags and the below file,

```kts
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

allprojects {
    afterEvaluate {
        tasks.withType<Test>().configureEach {
            testLogging {
                events(TestLogEvent.PASSED, TestLogEvent.SKIPPED, TestLogEvent.FAILED)
                exceptionFormat = TestExceptionFormat.FULL
            }
        }
    }
}
```

You can force logging of `PASSED`, `SKIPPED`, and `FAILED` logs while also printing out stdout (not currently enabled, but you could) and more of a stacktrace so you can see the explicit assertions from KoTest. I'm unsure if this is really the _best_ way to solve this, but from my digging you can't provide testLogging modifications via any CLI Args/Flags only through modifications of the actual build.gradle.kts file.

There'll be a PR to at least fix the first part and attempt to integrate the second change as well 😄

### PR DESCRIPTION
**Pull request by NickHackman**
Closes #36 

With this I think we're back in a mostly work spot! :tada: 

## Changes

- Custom gradle init script
- Proper Gradle test output parsing

```text
org.example.KotestDescribeSpec > a namespace > should handle failed assertions FAILED
```

Results in the Neotest Id of

```text
'/home/nick/GitHub/neotest-kotlin/lua/tests/example_project/app/src/test/kotlin/org/example/KotestDescribeExample.kt::"a namespace"::"a nested namespace"::"should handle failed assertions"'
```

Where /home/nick/GitHub/neotest-kotlin is my path to the plugin :smile:

:tada: :tada: :tada: 

## Future Changes

- KoTest run an individual test

I've been digging into this, but it's way harder than I would've thought? Trying to steal as much as I can from KoTest IntelliJ Plugin, but they actually run a custom plugin/app to run individual tests and don't actually use the environment variables? This may require a lot more digging to get this to work properly.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1 +1,2 @@
 /lua/tests/example_project/gradle/wrapper/**
+.luarc.json
```
Comment (NickHackman) [inline .gitignore:2]: Neovim keeps creating this json config file, so just gitignoring it

File: lua/neotest-kotlin/src/output-parser.lua [hunk 2]
```diff
@@ -1,140 +1,110 @@
...
-  end
-
-  return nil
+---Gets the result of a Gradle test output line
+---@param line string
+---@return string status passed, skipped, failed, none
+M.parse_status = function(line)
+	local result = "none"
+
+	if vim.endswith(line, "PASSED") then
```
Comment (NickHackman) [inline lua/neotest-kotlin/src/output-parser.lua:9]: Vim has an `endswith` function already written so using that :tada:

File: lua/neotest-kotlin/src/output-parser.lua [hunk 3]
```diff
@@ -1,140 +1,110 @@
...
+	end
+
+	local names = { unpack(split, 2) }
+
+	local result = path
+	for i, segment in ipairs(names) do
+		segment = vim.trim(segment)
+		if (i + 1) == #split then
+			segment = segment:match("(.+) [PASSED|FAILED|SKIPPED]")
+		end
```
Comment (NickHackman) [inline lua/neotest-kotlin/src/output-parser.lua:45]: Getting the last segment of

```text
org.example.KotestDescribeSpec > a namespace > should handle failed assertions FAILED
```

And removing the "FAILED"/"PASSED"/"SKIPPED"

File: lua/neotest-kotlin/src/output-parser.lua [hunk 4]
```diff
@@ -1,140 +1,110 @@
...
+	return result
 end
 
-local function escape_magic_chars(str)
-  return str:gsub("([%^%$%(%)%%%.%[%]%*%+%-%?])", "%%%1")
-end
+---Whether the line is a valid gradle test line
+---@param line string
+---@return boolean
+function M.is_valid_gradle_test_line(line, package)
```
Comment (NickHackman) [inline lua/neotest-kotlin/src/output-parser.lua:60]: Simple helper here to ensure that the line is one that we can parse and care about

File: lua/tests/example_project/app/src/test/kotlin/org/example/KotestDescribeExample.kt
Comment (NickHackman) [inline lua/tests/example_project/app/src/test/kotlin/org/example/KotestDescribeExample.kt:1]: This is all ktlint format

File: test-logging.init.gradle.kts [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+import org.gradle.api.tasks.testing.logging.TestLogEvent
+
+allprojects {
+    afterEvaluate {
+        tasks.withType<Test>().configureEach {
+            /**
+             * Force re-run the tests so we have output to parse
+             * [docs](https://blog.gradle.org/stop-rerunning-tests)
+             */
+            outputs.upToDateWhen { false }
```
Comment (NickHackman) [inline test-logging.init.gradle.kts:18]: It's advised in the article I linked as "docs" to do this, but we need the output every time; otherwise, there's nothing for us to parse

File: lua/tests/output-parser_spec.lua [hunk 6]
```diff
@@ -1,239 +1,292 @@
...
+				"6 tests completed, 2 failed, 2 skipped",
+				"> Task :app:test FAILED",
+				"FAILURE: Build failed with an exception.",
+				"* What went wrong:",
+				"Execution failed for task ':app:test'.",
+				"> There were failing tests. See the report at: file:///home/nick/GitHub/neotest-kotlin/lua/tests/example_project/app/build/reports/tests/test/index.html",
+				"* Try:",
+				"> Run with --scan to get full insights.",
+				"BUILD FAILED in 4s",
+				"5 actionable tasks: 3 executed, 2 up-to-date",
```
Comment (NickHackman) [inline lua/tests/output-parser_spec.lua:43]: This is nearly all the gradle output, I trimmed down the stacktrace. Just an integration test on mock data, would make sense to do say run this on the `example_project` output as part of CI/CD in the future?

**Review by codymikol — APPROVED** [review]

**Comment by codymikol** [comment]
Tested and reviewed! :tada: I' have to run, but I'll get eyes on the others when I get back, thanks so much for the help!
