### PR TITLE
fix: identify tests

### LINKED ISSUE #34: Fails to identify individual tests/file
These issues were mentioned in https://github.com/codymikol/neotest-kotlin/pull/33#issuecomment-2985746638,

Using

```
NVIM v0.11.2                                                                                                                                                                                                                                                                                                                    
Build type: Release                                                                                                                                                                                                                                                                                                             
LuaJIT 2.1.1748459687
```

I'm hitting the following issues,

- Test parsing sometimes works (after a couple saves it sometimes functions)
- When it does properly parse the tests I then get this error

```
neotest-kotest: ...eotest-kotlin/lua/neotest-kotlin/src/position-parser.lua:41: attempt to call method 'start' (a nil value)                                                                                                                                                                                                    
stack traceback:                                                                                                                                                                                                                                                                                                                
        ...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:89: in function 'start'                                                                                                                                                                                                                                     
        ...eotest-kotlin/lua/neotest-kotlin/src/position-parser.lua:41: in function 'get_all_matches_as_string'                                                                                                                                                                                                                 
        ...eotest-kotlin/lua/neotest-kotlin/src/position-parser.lua:69: in function 'get_first_match_string'                                                                                                                                                                                                                    
        ...004X7Y/GitHub/neotest-kotlin/lua/neotest-kotlin/init.lua:76: in function 'build_spec'                                                                                                                                                                                                                                
        ...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:76: in function '_run_tree'                                                                                                                                                                                                                                 
        ...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:65: in function <...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:22> 
```

@codymikol eluded to the issues potentially being caused by dated/broken features in Treesitter/Neotest (https://github.com/codymikol/neotest-kotlin/pull/33#issuecomment-2989269837)

### PR DESCRIPTION
**Pull request by NickHackman**
Fixes #34 

More progress!

## Changes
- Tests are now properly identified!
- Cleanup of some unused/no longer required interface
- Using new features from Treesitter and Neotest

Screenshot 2025-06-20 at 6 24 10 PM

## Future Changes
- Need to properly pass the test name when invoking `gradlew` (currently, `kotest_filter_tests` is always "*")
- Probably should ~disable~ remove the `--debug`  flag? It leads to A LOT of output. At least allow configuration of what' run instead? 🤷‍♂️ 

**NOTE**: None of these changes fix the

```lua
      it("should contain the correct short description", function()
        assert.is_not.same(nil, result_entry.short)
        assert.are.same(result_entry.short, "should handle passed assertions")
      end)
```

tests that still fail

### CODE REVIEW

File: lua/neotest-kotlin/init.lua [hunk 1]
```diff
@@ -8,57 +8,54 @@ local filter = require("neotest-kotlin.src.filter")
 local treesitter_query = require("neotest-kotlin.kotest-treesitter-query")
 local output_parser = require("neotest-kotlin.src.output-parser")
 
-local adapter = { name = "neotest-kotest" }
+local M = {}
```
Comment (NickHackman) [inline lua/neotest-kotlin/init.lua:11]: I don't really understand the purpose of this useless wrapper, but it's just lifted directly from

https://github.com/nvim-neotest/neotest/blob/ef492755730e59e1d8122c461abbd086bee4c76b/lua/neotest/adapters/interface.lua

File: lua/neotest-kotlin/init.lua [hunk 2]
```diff
@@ -8,57 +8,54 @@ local filter = require("neotest-kotlin.src.filter")
...
-  local definition = captured_nodes[match_type .. ".definition"]
-
-  local build_position = {
-    type = match_type,
-    path = file_path,
-    range = { definition:range() },
-  }
-
-  return build_position
-end
```
Comment (NickHackman) [inline lua/neotest-kotlin/init.lua:45]: This may be part of the old interface, but isn't part of it anymore and isn't used anywhere?

File: lua/neotest-kotlin/kotest-treesitter-query.lua [hunk 3]
```diff
@@ -1,46 +1,39 @@
-local TreesitterQuery = {}
-
--- These are treesitter queries for pulling data of of the AST,
+-- These are treesitter queries for pulling data out of the AST,
 -- More information on how this works over here: https://neovim.io/doc/user/treesitter.html
--- And you can interactively play around with these kotlin queries here: https://fwcd.dev/tree-sitter-kotlin/
-
-TreesitterQuery.value = [[
+-- And you can interactively play around with these kotlin queries here: https://fwcd.github.io/tree-sitter-kotlin/
```
Comment (NickHackman) [inline lua/neotest-kotlin/kotest-treesitter-query.lua:3]: Little bit going on here, but the URL that was here before (https://fwcd.dev/tree-sitter-kotlin/) was broken and is now https://fwcd.github.io/tree-sitter-kotlin/

File: lua/neotest-kotlin/kotest-treesitter-query.lua [hunk 4]
```diff
@@ -1,46 +1,39 @@
-local TreesitterQuery = {}
-
--- These are treesitter queries for pulling data of of the AST,
+-- These are treesitter queries for pulling data out of the AST,
 -- More information on how this works over here: https://neovim.io/doc/user/treesitter.html
--- And you can interactively play around with these kotlin queries here: https://fwcd.dev/tree-sitter-kotlin/
-
-TreesitterQuery.value = [[
```
Comment (NickHackman) [inline lua/neotest-kotlin/kotest-treesitter-query.lua:7]: Removed this wrapping in a table, to just set one property of the table to just return the String itself. This was being done in the treesitter/*.lua files by directly setting M equal to the String

File: lua/neotest-kotlin/kotest-treesitter-query.lua [hunk 5]
```diff
@@ -1,46 +1,39 @@
...
-    )
+      ) (annotated_lambda)
+    ) 
 ) @test.definition
 
-; todo Mathes xdescribe("context") { /** body **/ }
+; todo Matches xdescribe("context") { /** body **/ }
 
-; todo Mathes xit("context") { /** body **/ }
+; todo Matches xit("context") { /** body **/ }
```
Comment (NickHackman) [inline lua/neotest-kotlin/kotest-treesitter-query.lua:36]: Typo fixes

File: lua/neotest-kotlin/src/position-parser.lua [hunk 6]
```diff
@@ -3,74 +3,60 @@ local lib = require("neotest.lib")
 local M = {}
 
 M.parse = function(path, query)
-  local positions = lib.treesitter.parse_positions(path, query, {
-    nested_namespaces = true,
-    nested_tests = false,
-    fast = false,
-  })
```
Comment (NickHackman) [inline lua/neotest-kotlin/src/position-parser.lua:10]: Sorry, some of this file is formatting changes

File: lua/neotest-kotlin/src/position-parser.lua [hunk 7]
```diff
@@ -3,74 +3,60 @@ local lib = require("neotest.lib")
...
 
 M.get_all_matches_as_string = function(path, query)
-  local results = {}
+	local language = "kotlin"
 
-  local file = io.open(path)
+	local bufnr = vim.api.nvim_create_buf(false, true)
+	local content = vim.fn.readfile(path)
+	vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, content)
+	vim.api.nvim_set_option_value("filetype", language, { buf = bufnr })
```
Comment (NickHackman) [inline lua/neotest-kotlin/src/position-parser.lua:21]: Shamelessly stolen from https://github.com/fredrikaverpil/neotest-golang/blob/0a0acff3cf9a0bf140c84ea9e66d818df7c2608f/lua/neotest-golang/features/testify/query.lua#L57-L60

File: lua/neotest-kotlin/src/position-parser.lua [hunk 8]
```diff
@@ -3,74 +3,60 @@ local lib = require("neotest.lib")
...
-      if #row_lines > 1 then
-        print("Error: position parser currently only supports single line results.")
-        return ""
-      end
-
-      local found_line = row_lines[1]
-
-      local result = found_line:sub(start_col + 1, end_col)
-
-      results[#results + 1] = result
```
Comment (NickHackman) [inline lua/neotest-kotlin/src/position-parser.lua:60]: Don't need this parsing logic anymore, you can just

```lua
vim.treesitter.get_node_text(node, bufnr)
```

File: lua/tests/example_project/app/build.gradle.kts [hunk 9]
```diff
@@ -22,16 +22,12 @@ repositories {
 dependencies {
     // This dependency is used by the application.
     implementation(libs.guava)
+    testImplementation("io.kotest:kotest-runner-junit5:5.9.0")
+    testImplementation("io.kotest:kotest-assertions-core:5.9.0")
```
Comment (NickHackman) [inline lua/tests/example_project/app/build.gradle.kts:26]: Actually added KoTest as a dependency here so that you can run the tests

File: lua/tests/example_project/app/build.gradle.kts [hunk 10]
```diff
@@ -22,16 +22,12 @@ repositories {
...
 }
 
-testing {
-    suites {
-        // Configure the built-in test suite
-        val test by getting(JvmTestSuite::class) {
-            // Use Kotlin Test test framework
-            useKotlinTest("1.9.22")
-        }
-    }
```
Comment (NickHackman) [inline lua/tests/example_project/app/build.gradle.kts:34]: Kotlin Test isn't supported yet... removing.

File: lua/tests/example_project/app/src/test/kotlin/org/example/KotestDescribeExample.kt [hunk 11]
```diff
@@ -1,5 +1,5 @@
 
-package kotlin.org.example
+package org.example
```
Comment (NickHackman) [inline lua/tests/example_project/app/src/test/kotlin/org/example/KotestDescribeExample.kt:2]: Using the `kotlin` package prefix causes Gradle to fail the build immediately saying that only the Kotlin team/compiler can use the kotlin prefix.

File: lua/tests/example_project/gradlew
Comment (NickHackman) [inline lua/tests/example_project/gradlew:1]: All of this was done by

```shell
gradle wrapper
```

File: lua/tests/example_project/app/src/test/kotlin/org/example/KotlinTestExample.kt
Comment (NickHackman) [inline lua/tests/example_project/app/src/test/kotlin/org/example/KotlinTestExample.kt:1]: Don't support yet, removing

**Comment by codymikol** [comment]
"Probably should disable remove the --debug flag? It leads to A LOT of output. At least allow configuration of what' run instead? 🤷‍♂️"

Back when I was implementing this, the debug flag seemed to be the only way to get enough context to get the passing / failing / skipped status of a test along with the top level message and stack-trace. This could have changed for sure.

**Comment by codymikol** [comment]
Sorry for the delay on reviewing, I was out at a wedding this past weekend. These changes are looking good on my end! 

I still have to spam save the file and then navigate for the neotest summary panel to update. I'm suspicious that is an upstream issue since I can't think of a way the adapter could create that behavior.

I'll take a look at the open issues and report back.
